### ISSUE TITLE
[Feature request] Remove and replace resources

### ISSUE THREAD

**Issue by UnrealKaraulov** [ShadowsAdi/PrecacheList#1]
possible to add natives to replace precached resources or delete ?

(as in useless Ultimate Unprecacher)

**Comment by ShadowsAdi** [comment]
Not possible for now. It could be possible using an external file which stores files that should be unprecached / replaced next map.

**Comment by UnrealKaraulov** [comment]
Now no needed natives, even in reapi ?

Possible to hook SVC_RESOURCELIST message ? 

Example 
[re_precache.txt](https://github.com/ShadowsAdi/PrecacheList/files/8159894/re_precache.txt)

This message can be used to create/replace resource, even BSP (map) to another.

**Comment by ShadowsAdi** [comment]
Added an unprecacher in version 1.4: https://github.com/ShadowsAdi/PrecacheList/commit/f1b69d413e6d3d050d94bfee4042b813ab776f68
